### ISSUE TITLE
mattermost vs slack

### ISSUE THREAD

**Issue by djarecka** [nmind/hackathon2021#13]
are we planning to use mattermost instead of slack during the hackathon? are we moving  to mattermost permanently?

**Comment by gkiar** [comment]
Great Q -- what slack org is there already? I just suggested the mattermost to avoid adding another org to people's workflows

**Comment by djarecka** [comment]
we have nmindteamworkspace.slack.com but I'm not sure how to add you. I think @oesteban recently asked about it, so he might now who to talk to.

**Comment by djarecka** [comment]
having slightly bigger crowd during the hackathon mattermost might be better if we don't have an easy way to add new people to the slack

**Comment by shnizzedy** [comment]
@gkiar I just invited you to the Slack workspace. We could post an open invite link somewhere, but I'm not sure how public we want that workspace to be.

**Comment by gkiar** [comment]
@shnizzedy Good idea — could you get an open invite link ready, and we'll post it in the Zoom and Gathertown spaces? You could also reply to the email thread with it. I'll update the README to point people to the slack.
