### ISSUE TITLE
platform for web site

### ISSUE THREAD

**Issue by poldrack** [nmind/hackathon2021#15]
I've just recently set up a jupyter book system that automatically builds a site using Github Actions (from md/ipynb files) for another project - happy to implement it here if you want me to, while it's fresh in my mind - but wasn't sure if you had other ideas in mind for the web platform.

**Comment by gkiar** [comment]
Hey @poldrack — that could be perfect. Would you be willing to set that up in an `nmind.github.io` repository? I don't think there strong feelings for a platform, but this could be a great starting point. Happy to help in anyway, just let me know

**Comment by satra** [comment]
and https://nmind.org now maps to that.
